### ISSUE TITLE
Updated URL

### ISSUE THREAD

**Issue by MichaelBone** [planningalerts-scrapers/adelaide_hills_council_sa_development_applications#5]
The URL for development applications has changed from https://www.ahc.sa.gov.au/ahc-resident/Pages/Planning-and-Building/Current-Development-Applications.aspx to https://www.ahc.sa.gov.au/Resident/planning-and-building/current-development-applications (and although the old URL still works it could stop working in the future).  See https://morph.io/planningalerts-scrapers/adelaide_hills_council_sa_development_applications.

**Comment by mlandauer** [comment]
Fixed by merging #6
